# Generated by Django 4.2.5 on 2023-09-11 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tableconnect.company')),
                ('volume', models.IntegerField()),
                ('packaging', models.CharField(max_length=10)),
                ('is_recommended', models.BooleanField(default=False)),

            ],
        ),
    ]
